title: Perawins lovely website
theme: minima
author: Perawin

# Add navigation links
nav:
  - title: Home
    url: /
  - title: About
    url: /about/
    sub_nav:
      - title: Contact Us
        url: /about/contact/
      - title: Our Team
        url: /about/team/
